version: '3.8'

services:
  webapp:
    build: .
    container_name: andirbys-pizza-app
    expose:
      - "3002"
    volumes:
      # Volume nomeado: Protege 100% o seu banco de dados contra
      # as deleções do Github e do Coolify ao fazer redeploys.
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
    name: andirbys_sqlite_data
